[build-system]
requires = ["hatchling>=1.21.0", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "loggerman"
dynamic = ["version"]
description = 'A powerful, hassle-free Python ðŸ logger. ðŸ“œ Clean formatting â€¢ ðŸŽ¯ Multiple levels â€¢ ðŸ”Œ Pluggable handlers â€¢ â± Timestamps'
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
keywords = []
authors = [
  { name = "a.ntelifilippidis", email = "alexntelifilippidis@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "colorama>=0.4.6"
]

[project.urls]
Documentation = "https://github.com/a.ntelifilippidis/loggerman#readme"
Source = "https://github.com/a.ntelifilippidis/loggerman"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/loggerman/_version.py"

[tool.hatch.envs.dev]
extra-dependencies = [
  "mypy==1.14.1",
  "pytest",
  "pytest-cov",
  "pytest-mock",
  "ruff==0.9.2",
]
[tool.hatch.envs.dev.scripts]
check = "mypy --install-types --non-interactive {args:src/loggerman}"
lint  = "ruff check ."

[tool.coverage.run]
source_pkgs = ["loggerman", "tests"]
branch = true
parallel = true
omit = [] # Omit nothing by default, but you can specify files to omit here if needed.

[tool.coverage.paths]
loggerman = ["src/loggerman", "*/loggerman/src/loggerman"]
tests = ["tests", "*/loggerman/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.mypy]
ignore_missing_imports = true              # It's the default, but it's needed here for pre-commit.
strict = true
namespace_packages = false
enable_error_code = ["ignore-without-code"]